@host=https://localhost:7183

GET {{host}}/decks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZGI2N2MyMS0wNDVmLTRlYTQtODQ5Zi02ZjMwZDY2ZjhjZjQiLCJnaXZlbl9uYW1lIjoiTmljb2xhcyIsImZhbWlseV9uYW1lIjoiUlVCSU8iLCJqdGkiOiI2ZWQ4ZDMxZi1jZTY5LTQ4ZjItOTM3Ny1kODAzOTI3YjllNzYiLCJleHAiOjE2NzIwMTQ5MDQsImlzcyI6IkNvdW50ZXJEZWNrIiwiYXVkIjoiQ291bnRlckRlY2sifQ.CVympQy24TG-rb8bLgkad77-kTqp9-NTfMtPwOwgUKo